### PR TITLE
Game page

### PR DESCRIPTION
**Pull request by RINO-GAELICO**
Finished the main structure of the game page. Also added some partials (header, footer and a navbar).

Modified the root page to something more meaningful, just to keep track of the work done on routes.

I also tried to match the content of the rest of the files (package.json etc).

Please take a look and let me know.

### CODE REVIEW

**Review by RINO-GAELICO — COMMENTED** [review]
Let me know if you have any questions

**Review by justin123yu — APPROVED** [review]
I don't see any conflicts or problem with the code.

**Review by laerfugi — APPROVED** [review]
No problems with the code.

**Comment by datvosfsu** [comment]
no questions

**Review by datvosfsu — APPROVED** [review]
no questions here

**Pull request merged**
